name:                benchmarker-cli
version:             0.0.0
github:              "benchmarker/cli"
license:             BSD3
author:              "@iamogbz"
maintainer:          "iamogbz+benchmarker@gmail.com"
copyright:           "2020 @iamogbz"
category:            System, CLI

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/benchmarker/cli#readme>

dependencies:
- base >= 4.7 && < 5
- criterion
- optparse-applicative
- text
- turtle

library:
  source-dirs: src

executables:
  benchmarker:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - benchmarker-cli

tests:
  benchmarker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - benchmarker-cli
