#!/usr/bin/env sh

# Based on conventions from https://github.com/github/scripts-to-rule-them-all
# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

# Setup package
stack_setup() {
  echo "Stack package setup"
  stack update
  stack setup
}

# If stack is not installed then download and install
if ! [ -x "$(command -v stack)" ]; then
  echo "Command 'stack' not found. Installing..."
  curl -sSL https://get.haskellstack.org/ | sh
  stack_setup
fi

if [ -z $NO_DEPS ]; then
  # If yq is not installed then download and install
  if ! [ -x "$(command -v yq)" ]; then
    echo "Command 'yq' not found. Installing..."
    if [ -x "$(command -v snap)" ]; then
      sudo snap install yq
    elif [ -x "$(command -v brew)" ]; then
      sudo brew install yq
    else
      echo "Could not install yq"
      exit 1
    fi
  fi
  # Install extra deps
  echo "Stack install extra deps"
  yq read stack.yaml 'extra-deps[*]' | xargs stack install
fi

# If not in CI
if [ -z $CI ]; then
  # Setup precommit hook
  ./script/precommit
fi
