#!/usr/bin/env sh

# Based on conventions from https://github.com/github/scripts-to-rule-them-all
# script/bootstrap: Resolve all dependencies that the application requires to
# run.

# If not in CI, we have to install the correct python versions
if [[ -z $CI ]]; then
    # pyenv update
    pyenv install --skip-existing || return
fi

VENV="${VENV:-.venv}"
test -d $VENV || python3 -m venv $VENV || return
. $VENV/bin/activate

export POETRY_HOME="${POETRY_HOME:-$HOME/.poetry}"
curl -sSL https://install.python-poetry.org | python3 - --preview

if ! command -v foobar &>/dev/null; then
    export PATH="$POETRY_HOME/bin:$PATH"
fi

if [[ -z $SKIP_DEPS ]]; then
    poetry install
fi

if [[ -z $CI ]]; then
    python -m python_githooks

    if ! complete -p invoke &>/dev/null; then
        source <(inv --print-completion-script bash)
    fi
fi
